#!/usr/bin/env bash

brew update

brew upgrade

brew install --cask iterm2
brew install --cask macvim

brew install the_silver_searcher
brew install rbenv
brew install tags
brew install wget
brew install fzf
brew install git
brew install rbenv
brew install tmux
brew install ctags
brew install wget
brew install zsh
brew install direnv
brew install heroku
brew install youtube-dl
brew install xz
brew install ripgrep
