[font.normal]
family = "FiraMono Nerd Font"
# family = "Hack Nerd Font"
# family = "JetBrainsMono Nerd Font"
# family = "JetBrainsMono Nerd Font Mono"
# family = "MonaspiceNe Nerd Font"
# family = "MonaspiceAr Nerd Font"
# family = "MonaspiceAr Nerd Font Propo"
style = "Regular"
[font.offset]
y = 8
[font]
size = 18.0
[env]
TERM='xterm-256color'
