return {
  { "Shatur/neovim-ayu" },
  { "shaunsingh/nord.nvim" },
  { "joshdick/onedark.vim" },
  { "Mofiqul/dracula.nvim" },
  { "shaunsingh/solarized.nvim" },
  { "catppuccin/nvim" },
  { "nordtheme/vim" },
  { "NLKNguyen/papercolor-theme" },
  { "rebelot/kanagawa.nvim" },
  { "rose-pine/neovim" },
  { "shaunsingh/oxocarbon.nvim" },
  {
    "craftzdog/solarized-osaka.nvim",
    lazy = false,
    priority = 1000,
    opts = {},
  },
  { "loctvl842/monokai-pro.nvim" },
}
